### ISSUE TITLE
foreign keys

### ISSUE THREAD

**Issue by ghost** [probertson/air-sqlite#16]
how to work with air adobe Foraneas key, your library does the job?
greetings :dancers:

**Comment by probertson** [comment]
Adobe AIR uses SQLite. For foreign key relationships, just do a JOIN statement between the primary key of the table and the related key of the foreign table -- the same way you would with any SQL database.

SQLite doesn't have foreign key constraints, so you can't have rules that check automatically if a foreign key has a matching primary key in the related table, or to automatically propagate key updates or deletes. You'll need to code those relationships yourself. One way to do that is with triggers, which are supported in SQLite.

In any case, this library makes it easier to execute SQL in general, but doesn't add any extra functionality (like foreign key constraints).

**Comment by ghost** [comment]
thanks for the quick response, well I have a table topics table topics and this has many categories, when you delete a theme would also be eliminated categories containing the deleted items table, I'm a little lost on this issue, as it could ? , And thanks again :)

**Comment by probertson** [comment]
(re-posting this to fix the formatting)

You could add a trigger to the "topics" table with a "BEFORE DELETE" 
that deletes the related records in the categories table -- something 
like this (note that I'm not actually testing this so my syntax may be 
off):

```
CREATE TRIGGER delete_related_categories_when_deleting_topics
BEFORE DELETE
ON topics
BEGIN
   DELETE FROM categories
   WHERE categories.theme_id = OLD.id
END
```

You run this statement just one time, after creating the topics and 
categories tables, and the trigger will continue to exist until it's 
deleted using a DROP TRIGGER statement.

In this example, "topics" is the topics table, "categories" is the 
categories table, "categories.theme_id" is the foreign key column in 
the categories table that corresponds to the primary key of the themes 
table, and "OLD.id" refers to the primary key of the topics table. 
("OLD" is a built in alias for the table on which the DELETE statement 
is being run.)

This trigger would run when you do something like this:

```
DELETE FROM topics WHERE id = 25
```

or

```
DELETE FROM topics WHERE id > 5 AND id < 27
```

Before your DELETE statement runs, it would run the trigger and delete 
the corresponding rows in the categories table. In the case of the 
second DELETE statement, it would run the trigger code once for each 
row that's being deleted.

**Comment by ghost** [comment]
thanks a lot , everything is working well :+1:
