### ISSUE TITLE
Too many SQLConnection objects

### ISSUE THREAD

**Issue by probertson** [probertson/air-sqlite#2]
Add 2+ statements at once. It should only create as many SQLConnection objects as there are statements being run (up to the maximum). However, it creates more than 2 (or however many).

**Comment by rudimpc** [comment]
So what are the consequences of this?

**Comment by probertson** [comment]
The consequence is that it ends up creating more instances earlier than you need them -- perhaps even creating more than you'll ever need. So there's additional memory overhead from having the extra SQLConnection objects.

On the other hand, if an app is going to need more connections eventually, then it does have a possible benefit of pre-creating the connections so that later you don't have to wait for them to be connected. I'm going to create that as a separate enhancement request so that the developer can control which option they want

**Comment by probertson** [comment]
This is fixed in v0.1.1.1 (commit 0819fae9ec3c873935da56082a066f5df6617271)
