### ISSUE TITLE
PendingBatch problem

### ISSUE THREAD

**Issue by rudimpc** [probertson/air-sqlite#3]
hi,
I encountered a strange problem with its latest version. In PendingBatch, in the function beginTransaction after some time of inactivity, performing _conn.begin  does not seem to follow the event SQLEvent.BEGIN, so the function conn_begin not invoked. I can not locate the problem.

**Comment by rudimpc** [comment]
any ideas?

**Comment by rudimpc** [comment]
help please

**Comment by rudimpc** [comment]
I have find this: http://www.pubbs.net/200911/flex/815-flexcoders-air-151-transaction-issue-when-begin-is-called-it-doesnt-do-anything.html
perhaps the same problem?
can be a problem of air? someone knows something?

**Comment by rudimpc** [comment]
maybe I found!
the problem seems to be the SDK!
Now with the latest SDK version, my application seems to work correctly!
4 days work to find the problem! ADOBE !!!!!!!!!!

**Comment by probertson** [comment]
Sorry for not responding sooner. Did it resolve the problem to update to the newer AIR SDK? What SDK was having the problem, and what SDK was it fixed with?

**Comment by rudimpc** [comment]
the latest version of the SDK are here: http://labs.adobe.com/technologies/air2/
May 11, 2010
the previous version 2.0beta2 does not operate correctly for transactions with specific data (apparently the problem is to use dates in queries).

**Comment by probertson** [comment]
It seems that this was a problem in AIR, so I'm closing this issue
