### ISSUE TITLE
Progress counter is wrong for executeModify() progress

### ISSUE THREAD

**Issue by probertson** [probertson/air-sqlite#8]

**Comment by rudimpc** [comment]
which means? what happens? the system crashes?

**Comment by probertson** [comment]
Fixed in commit: baa649f218f57e81d8ce9f18d0b5c0da9982082e
Included in v0.1.2.2

**Comment by probertson** [comment]
Correction: this issue was not fixed in v0.1.2.2. It was fixed in commit a8a811ad04164eabccfa8d9ed97e2ac65b2fcc03 which is included in v0.1.2.3
